ALTER TABLE addresses
    ADD COLUMN IF NOT EXISTS street VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS ward VARCHAR(100) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS district VARCHAR(100) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS city VARCHAR(100) NOT NULL DEFAULT '';
