apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
stringData:
  postgres-password: change-me-db-password
  rabbitmq-password: change-me-rabbitmq-password
  jwt-secret: change-me-jwt-secret-at-least-32-chars
  grafana-admin-password: change-me-grafana-password
