const homeImages = {
  hero: "https://lh3.googleusercontent.com/aida-public/AB6AXuCPKv1CtBwPM413euox0uKnxmUXjsuyZFpFIvDMoW9tfefpHVd_8BFtHSEnUjm5XAQu4WMkS8vgS56v7kIQYWar2OBBpzOurqNCin2KoM1hYEZHvbpagIiz8m2nCidCAiRbDaeJLBNHxra37cwt7QEG3UlOcKbs-W6WuTDZj3qjg9hWIs2YR26l-ijHVnj8ck1-5NDhyVXXQECwDKQJs1i-nYT93ubM2EFutXuxPWxUHWH2o2Zhbz_naP2SXRRL50t8HcB8sUf5LXiX",
  menTile: "https://lh3.googleusercontent.com/aida-public/AB6AXuCyUfebOMONTnvYr9ZpAON5r2sqH9cixvFEI4IUO1HgtLokw0DocOKis15vSsJ14j6mnx1QrXMXJyDrzK64DrNUI1kc34lTyj4aIPfoodV3MFa0JLPFNdllb_6HgGOigtKyydUohURWyjMOQURKHAk5z02a5vuIH_t821X1vUIusV9VajR3V14-QiTAt7WCragHu_ErX2cBuxj6cZyi0qHNw-tRhFozQO02eRzXwXB3GyXDgg6tVkt9BgTiuPHfPlE9ZdYH2sNodvYW",
  womenTile: "https://lh3.googleusercontent.com/aida-public/AB6AXuBfeL88OBqW4Ue3Wr45J2UYNHHoz1V3GIYVT6BS47pFs4Ts1ZtnuMaaioY1y7Je7oqhcYL8DLZR8KKa3pevzh2EOXaCo_M9xAJhHsGvxIeawRZyLgrBDcTQKiMMTdBJfJv4EDGj_ST1SAVOcoV-DlbA_GhmqAhboruBHvNNSjrLZExknF7AnbpG7f-BfdcG52rKGirTBwXdWoxBIaSFpozclIZ4oni5B5b2Xn7rzo1a13KiUEDsW12kfxNX2AN9xi_LfBWp-G8i2o7n",
  footwearTile: "https://lh3.googleusercontent.com/aida-public/AB6AXuC35EijN08hEhyXUNWU2WpmdXA-xKjXvVdQOkMB4J5Rt7XVw2ILNt27Jt92PUK2lOZLOyi-wwd64M20h4a_trllHLaecxpEhm3cRJskDeuyLTz248X3saxiF9Xx7qHWTTV-Q_6G58RaZiu-8vk3yYYOiP5aflLpGRjTe6yi6EtaoQKcBvHljgI4ItMv4FXnUPfGAYVnlVFrxYoDYB6LIE9tpXNeScpgugQTJzhp_icbkXy4Ay2kMR5-SI0rGXdV2RyT8p-AYS9ZdH9w",
  accessoriesTile: "https://lh3.googleusercontent.com/aida-public/AB6AXuAtpa0mJyKNICckH1wefUZTbwZo2Cg73toQg0p8Gs8HN84jU1dorhR-2jnXY-oDpZbRJQTYU6z2RuFiaqR_vx_BDTT30cUs2PtZGI-fdDfLZlrhkBB-gyED-FFOC2t0Dwpfe2t6mBWGbfA-f4EbYvH1QV61hKuBF7UfI-b_NBaRjm_A3LejyFwwwvM-2t-K-zHQWiYcOHHbplLjNpn3jDEO4siwrnpdkAaVJDh28LrLN0qGfUWRCFcXRzKfNM5VvnVj7r3R8bZe5FpI",
  callout: "https://lh3.googleusercontent.com/aida-public/AB6AXuA-QCiHmdCOxRlVT1rixfgiaLjtOyUpf_qCwS4N8rEMGTTVyJxqkHxQ1iiUeTIIjM9C_MgASpIzwLXa8wLI7ck0F5p1lc6AA6MfKkb3aN_Nbw5AhWsU9lBPxRcNlN7vOcvcId55iSoZRYNe8TCXUI_PC9zSeiPi6-O2ojrYX1RkopzPM8W9xTFEi3rS1s2qZ8IvVBPlgiJak9SR8Bp7wD71RSztHJCzs3MKTW0TNUGEn5sxJF68kLn8MLi1Kcp6ODrKfOGHNtCZKygx",
};

const menImages = {
  hero: "https://lh3.googleusercontent.com/aida-public/AB6AXuACWMir-mH0L8UXbUXQWypp-pFR6ldBwMeB_P57xJ4h6lF91JgCYYyEJ27pPIbRuST3wzOd8tibscQ-NbIurAXAyGOUWfZstI5mdT9d5_jh6VLXet-x-y-OPWmMV69qNvZALg2WhY1PVY_SFZnR1pxtNpFxR9lsyyLR7XmqRbJ_dhy0WQE2rK_YiUzI2TXstgAkQ537sWLyCCgyHe5Z2QW16TODc2jAY392leqTD0jFdmPyw689W_PhHTFoOURRakfD2ODeVuxVtb-u",
  one: "https://lh3.googleusercontent.com/aida-public/AB6AXuBRTlahnsv0f7ya3xU5YTERBeygNv3B_6MEExHsUzTI3uGv3gn9RVVaVkXFHJAQIYeO-NnQ-n51wqkjA-oml_uoLI96mxp1piJxtPHA5ofpE_9tSdHTMa8lNfjCgdbUOSRi__Y4J8VFSz5HhI5ZB9C5Vl5zl-6FxNxhAYwEDNV_XOP2dGsj5rTUtGDd1a59qGSue1hdS28wAOq4_SpG152HGpLir9kJsPtGA9trmPt5raubxkNMY1AI1cI7Qs5-pnKuSFT_JrLZrEaz",
  two: "https://lh3.googleusercontent.com/aida-public/AB6AXuA004mNLReNQb9OI2U6JwpX4idr5HiAL2OAqj-X2r60qRDaMIYLE7YAWWdvJ6_uvkh1jgDweWN2QRC0Z6CnAXNS54x6M_Qkf8uPtTr4G6Cl5-Y5z8iuGvbIv1u_DCawCRbkf01JSFMi_iZ2APFb_m56yIPq8-_Ap7HY-QbhgAL2tc-tsE4VsnyibszwQjgYBz28AGgGUIIQ7EDmY1bXGdkXyNQI991VG2ouIlVK-wOCqK_Lq8GNj4h27eldl1LjnR6Wt903BlKnHCVn",
  three: "https://lh3.googleusercontent.com/aida-public/AB6AXuBXRSWOWcHtCNyaMDYLCJzvRD_aYObkVBkIHPoz_HZOOuihWxPKo82MAX7anUmfBqHwOgx_6YthGokOn-aqEtAkMya3di9RNTlqqA2-zqT6x85Yh0CGWy5_gOTjOOMYxnRJ7B8A9ihZaMR-PzIAILb7T5rSMUCiZ-3CZRTX_u3XxJpOlXlYjWEZj4aFLaV_mamuWkKjkhTxSRpw7LyICx9lPITcKUuGOxJ0NkpKweDI4rMjqFkSSGZJssErigmmpbKq5Z6kLPVUehXg",
  four: "https://lh3.googleusercontent.com/aida-public/AB6AXuDBowt2AR0QGkZ_teHLK0qG2iUl8fGSUuNTrZHreU_s95xtmrbnCTB8LYOShnHaraaNDqoUnziBnVe2Rh6OAlJpU9ZSpF84L0-k23aokXc6aJdWswRdyGowycFswnENPgO9tfnUyUaMa2VjW8lGJYkmhPbnJhSE0zC0BdoSTdae8pmGnQwaAXzVlJJRhWYysiO1yf2n_lREj8nVxarkGub1OLnfLI4QrhAiAGV-AZTWnZg1MCqdpNi1pBSjb6RIPFAzXw0h_iTQCqrp",
  five: "https://lh3.googleusercontent.com/aida-public/AB6AXuDb4HgZThk-i_juM7LnHT28IvYp6L3O-BYlcwDKgfj8NoIfTFFhOF2Ole0eBVsqpYg3jj_0TeLOFVAlmWeCOqcLhMrp0WOXtTgYUke-t7sj7lC-e4jEl3lE8aZs01lCVJenptBJf3Fh0f1sdTVQ9W0cWZD8hEtVjX-LK-Bsqoc2UzdzkTUWeVjp7hrhjMGZhuTtvQ56nTXVelw9_F3p1d8ryVxqAzayeUimjbfSI8FHukDr7r45A4VjAJ3lpymfXulGrEM83TxdK6Sj",
};

const womenImages = {
  hero: "https://lh3.googleusercontent.com/aida-public/AB6AXuCCHjHHNBD0bZoSfUrXMIUsusvSJpfmxcJRzVyGEWriuKDCynB8NOcLil0MHJfUCfgjmGv_IMPAfbmEm73hz3s6Y6ycMQrKq1qnMzNHz4QbDczvsSfdf8SaL9vw3qoSEt36Xm52OFG4ej1BLs2XxqsJW_tPT1C2xruIyndF6i4KCKATXFKExblf5UqEURDlAYRnWNDYbLXe8GGoCndX4q2IeRKAuk6Etam3vFkW85HI4vZvrHKCLYN63hA-DGdTKTpY9k-VBO3aY4le",
  one: "https://lh3.googleusercontent.com/aida-public/AB6AXuA2sL_3eVTxv8pTPhQFFFpSQH6Kaq9or00Ox__PprWsxnH4iFcdyvkF6yE_uLy_crNRWln5sUDsqQmSo-iayh_0MyCYYTR20XSGjWAB-uNe6duE69pSu714RVSt74tQMEIF3fuTduw02xllANi1JDAtn12UeUh9ljLf8hz3xi6jPfnSdYWCX7w9y3IwSDyovmYmtsxb0x9P-3bKU5qLNiMw7cc4_t2zNEpT8QLPRQLTFIXGR2WRSQbgpFitN5ZgjO-BIsY_4Wyg7jRS",
  two: "https://lh3.googleusercontent.com/aida-public/AB6AXuBmKXEwtGPg000dRd0DYpkc78_z_0z7Q60H3fju2rnkDAllnKGSFzesSqKvn2OqncI_k-QRIvUyfVSm75I-UKw3DhxiM5eOINn4C-vJnvj2z8uKIL2AqGnXgvmqeYEEzJ5-il3zT3BTGt9iPabLxhcPbK9AwTzCM3Z9Fo3vrhfReTlHCTZ3EIgs7_JxhOFfmrNerCamtXr0QKPKlok1p5W71S8CFoXMlgrk9yrqe55hyi8oG24OwLIfOD6sAGZDuAtdrYmvQ0QD-hzg",
  three: "https://lh3.googleusercontent.com/aida-public/AB6AXuBEKFEZ7Xk7Fyqc9Uf8Rr7JfhPIghhY7j0HO6bqSglckdRAUU1XFK1Vy_uPXAbpLqczXmCH41FFfT4QIgBtt7oBHhaEojRqYoMhEeW0zN9yDlgFxnnAhZfa_FjmfnZNakXUp-HAT6D2gb_BUeHA5TXBmMVsObd_AHQfOwPuMZTKrAqSkXnJe60KUnlOWajJ6btQ5zyNadwls33tVZNcDlHyJ8_EUlUAhHRtQ90ZhEzMNN5Mzjf_Hr7Onn7MZF-hkz45XkPrdm6pngSw",
  four: "https://lh3.googleusercontent.com/aida-public/AB6AXuAULIeOGtZd7vXZH0gSJHWiv3w1w4d6Tz7E7Y55Pp0wpbrudgRPkQEUxLNJ7z1iX2ofjNS4KSwbIFdzRgJR2rZEzslEi02TskRTUycOtweLNiBcTRv0RAiCUncTPXaXvHGzovAfwglQIxRlDavgkG0kp9z1__77ZtFulQa4AVlvR_muVhFSILTRpDDYMIgzrzsCEPjKJNyVc0k_NtV_qrK021aTU5RlI_Mg4TBu8JIzJLGkLHTEGfvWBezAYGbi6wNp_bgFRdeYEwST",
  five: "https://lh3.googleusercontent.com/aida-public/AB6AXuAaOoy5mPR6kERrz2pjB05mC0JlxtRtsf2hinDbaZYFD7RKSJI_OTZn_SVo1D7JP85uSvsIZaQ5ebu77UNrwEjYJZhP6gfcKLOHkl-z5NFjTzCwUsmsvv1WbILS5HtKtmz6D5YPmeIASNcfDev_nsQcB5Odi4O5svKDuTAkJyHAlgm2j2VUKiwX_XzxOMsMjnnzRdyJcj-olztbGq4uYqe6FRhYp04lXvSqa4dkOjD9RZ1tB8UYpCw_Jj4C-Vwk4eokTl5ETem6rnWz",
};

const footwearImages = {
  hero: "https://lh3.googleusercontent.com/aida-public/AB6AXuAFXvDME4hl86EBAExrs0TPuPyrDnhtwEb8MCDCvjzu2OS-kjWnUF7XkqwYs0MGf5WGZS6B5xPKLv0OXCG5ZrDjkm-McNkALLC0DCYp5LC9beGhY0SnzFUMFF998AElRWMoxze_NVDcZ1jJ4qerfPiE1xI5Xjc0Euy-lzfbdQzjbDW9gtsemGrCxPBq4MDAxVn_PdqcdHWaZ05cl7EMLinkvr6U9D8RGxe-UFtVaee5Q6n-Ohev-vr9h8DwExyawlWEZa9kUKDqsxlQ",
  one: "https://lh3.googleusercontent.com/aida-public/AB6AXuAMYKBjYQhfEPiX1rrzGJqP-bZ3N-za3aIYrq4ZJ7iHUOBBELUJUpvBk3Ms1bHaAXBuEZwTIczKGpjLz2AbAXSyAma0h_FRPa4MA_RgE9EO-SCavieX4XPDLcnuloZs8tAGD5FGHlcBtSszlVWYz-FA-hca0gi-xkAC4k_vrZmULdCAPQNXUhSbE3wrhj8_XgthXU6Aso4ltg4ME3nEgOsgEaBDUB6hKvQ_Ere_31vsZ98zkTq0zGrgjNqUJHCDPBUQPmqG9Q702KKw",
  two: "https://lh3.googleusercontent.com/aida-public/AB6AXuD5KVhgLop51bisay_zrsW8YVtKdD2et-udRx64dbQtp0xYp4CE38R94dLqJO460aolSqy9UdPhfvdjSyjzz7Bbh4MOeBkHbehqlMCTvPNv4PLXn3wFu6XqNIM_5UyUXX71NRni2ntQt4twbRrDvUPUi5cDXb-939ibHoOeSHMsDghYNOy7kZp5gd14kjIf6WUveYq0O9RFsuf5oY9RK1U9jhhlcJ_HJPXAwSBdNK2y67FH0n0MdcVNPoEwpIxvSAkUOZdh9YgdL7FA",
  three: "https://lh3.googleusercontent.com/aida-public/AB6AXuAAhJretAaN4nn0hwa-S3geRVjspqi5Iysp4o9wJ6Umsp05BfiGqmXjoyIkxI-iO9bJQHh6aFW1ByRoH4hP6tAQ1ifpRkG88XfFjHc7Tu8bEt310kgkBdS8l4wXyGN477geZFXoBXA7tpLWEx-ySFm69csgvDnFB-DbTmu1Va59aScYOFNkVt4WimRi19ZpDNf2YvhkDC8ETmf7ZpivWgg0fG1e-5cX386ZaOUDjcQ35GqrXeknlGJ-ig73LknVdiR_VbQ_rfBrjtto",
  four: "https://lh3.googleusercontent.com/aida-public/AB6AXuD4G3y0ZNdrqZS0ATojfSYa5t42Vrrx476FUX5qzvdCm_CCtF0C5yrINsDw4_G71jrBcMmaoueccHcMXO1xws91KQPeOyvLKzB9nAJZ70r7sO7YUn_u5DMqM93aUESLHoGVqBzejgzYA6j31SfDmrQl3IeBeL-xTBwhgq4AG_zSgROd0lwpbM9okRm26Hm2PbSk7bsL6aFYLo561VTjxiVDA_m28FuAt2wvBZpwLQNP23z7cESJyuNoMgdIyfHRBsZerL9BQbZ5D2p1",
};

const accessoriesImages = {
  hero: "https://lh3.googleusercontent.com/aida-public/AB6AXuBlb713Ad1ZqSwci4xtZudIi3pLSP2LntjrYOZbjlMC3NLKbFllzQBjpelA2EcNqh24qXtAEpJDAyVB3yIDQIFXvkmKD86_5kVoAVPrMjID1bCAWG7fccKmwcS9kJ41ohvAPtYZJCMl2fOWYpy8JLZLlE7ksjMmFK7UnFdxUeGvbhsRltWVAsAFxPv7hkz1uizaDdvr0s5HWGulhxwsX6bDRakqRxoA2bYrvMeQA0Nta95LkdO9PMTmAYDvvqhCUeQTFYjDd4sXr9q0",
  one: "https://lh3.googleusercontent.com/aida-public/AB6AXuBBESdqWOWSR5qEzSZhDSiYksfl92Z2-nXfieKv7zls3FB-7JuZVx-N6rXRCgkpMkJyxFCIzvAJAfUETLq2m7IDhOFmOtlLXZ9qEspJxSM3dIgXBbd3dzVswFhn3Y0MqayyDJYGSylH-MIjZnLLMaswkecd7-JUIltIP_szY3CTjkboRukxyb0Hicjh_fTS7Q8NRXCPfvyi2Gd8UjbveWvWIIUauI-d4h0ra0W790prCr-I9666OBdQ8zWwoQM8OSo6iYMbifIvLw2n",
  two: "https://lh3.googleusercontent.com/aida-public/AB6AXuCJ_mIoxtuOYX0UmZ6fp1vpG_etnXOkuxN0sOW8aXUVddHj5eDEGxKoK_oij-8jI8EDqrG_IXPuR5HXX_5FgjnVIMXKR3rvffkz_2hI2uHpAzMIbNZASVlBgA47Ecvrg53PTIsx8zim-xN9ZKFMoR3ivhIQDQ1jUJ0fFx2scgrGApYeeDOx-irk-VfW38VMHIZ4QMUtn6sXwUjEJRXtZ8dTLBnKQVPGxBzf7oOFEbYGY_2P__2xLjofQjJvPkwrIzkn9OjMEUgKEC2O",
  three: "https://lh3.googleusercontent.com/aida-public/AB6AXuDclyoI7lW_Aez2lBayMz4ES5BVdH-wo43IL4ZwpD4HLQkaJqfV3eDM-qMUs4V8Uyl6BTZ9FSNg7ExFisE6J-TMxcflCy5mFritcP54bDT49eqwGnwGnsOeheOgbCmpdtfGvnHaqpfmRpU4zQvBD7B4tmigGgv7hCDEHWLojIzOlAfe5p-0cCnzLjktClPIw5lG6h2qfT0buVNcsY57FFriSrjdMpV_jPcwn3Dwsz1C-8IS20dhOYE1-Kak6Hi0R-OiEeULdIqMBj2c",
  four: "https://lh3.googleusercontent.com/aida-public/AB6AXuAc-xgefZmjRHW4tYawNPs3ljWfgQ66YMBuFgX39XflOo-rQyjbJ2Ju2V0nLkyj2SVuz2BKsp1ucM74P4Gg2Q-TiJKsqrjsQRpxYORvaVExN0KFMkAU9KQFmWEmtNZHK5dm7iBBb1zYMTsluHO4Em5IwIi3lS3JGSUeU_unqmYgh-Fw65tcUaH2Ywxl8ag7h1znu1rGefQrkuDTARLHNwtQdpiGPKWCCp8JpO_yLO4kKGzLmwj8g3VfRzxs02GzkmBt2St6l1zyFYZU",
  five: "https://lh3.googleusercontent.com/aida-public/AB6AXuDwib-yVKWuTMsi4heheiLMLuw3Aukcrj4t8F5TLsWcUDULrkliTF_b5hFcyekqcaoBOrRCOob6yU3tV5aJCQChHBAggBedojt1THWZ_F-1GiBclBPJw389BrO0MvSA5xrOo1ssievm9rXO2UiIT0Ix_tHvr6rnGAPSAVNt1DYmLJVg_7vuvdan2zI6d3Z7JsuFwAqcipqjdi0FbCpFwqD4d7bZrq5JeL4i4aGx5NsOkOBZScx3UPHkR_rmJldHJi3Cb4MoiZaIoNsN",
};

export const siteMeta = [
  {
    brand_name: "ND Shop",
    footer_caption: "Crafted for the Discerning",
    footer_note:
      "Workbook-driven homepage synced to the Stitch editorial direction, with each image URL editable in Excel.",
  },
];

export const navItems = [
  {
    position: 1,
    slug: "all-archive",
    label: "All Archive",
    href: "/",
    is_default: true,
  },
  {
    position: 2,
    slug: "nam",
    label: "Nam",
    href: "/categories/Shop%20Men",
    is_default: false,
  },
  {
    position: 3,
    slug: "nu",
    label: "Nữ",
    href: "/categories/Shop%20Women",
    is_default: false,
  },
  {
    position: 4,
    slug: "accessories",
    label: "Accessories",
    href: "/categories/Accessories",
    is_default: false,
  },
];

export const hero = [
  {
    segment_slug: "all-archive",
    collection_kicker: "Winter 2024 Collection",
    title: "Forest & Hearth",
    description:
      "A tactile study of survival and comfort. Rooted in deep forest textures and the warmth of a mountain refuge.",
    primary_cta_label: "Explore Collection",
    primary_cta_href: "/products",
    secondary_cta_label: "View Lookbook",
    secondary_cta_href: "/products",
    background_image: homeImages.hero,
    quote_kicker: "The Technical Edge",
    quote_body:
      "Microservice-driven inventory ensures real-time availability of limited atelier pieces.",
    accent: "#cbb8a2",
    arrivals_kicker: "New Arrivals",
    arrivals_title: "Seasonal Essentials",
  },
  {
    segment_slug: "nam",
    collection_kicker: "Editorial Category",
    title: "Men's Atelier",
    description:
      "An architectural study in silhouette and structure. Crafted for the modern artisan.",
    primary_cta_label: "Open Men's Atelier",
    primary_cta_href: "/categories/Shop%20Men",
    secondary_cta_label: "View Archive",
    secondary_cta_href: "/products",
    background_image: menImages.hero,
    quote_kicker: "Atelier Note",
    quote_body:
      "Structure, restraint, and material depth staged with the same rhythm as the Stitch editorial system.",
    accent: "#a98567",
    arrivals_kicker: "Men's Edit",
    arrivals_title: "Structured Essentials",
  },
  {
    segment_slug: "nu",
    collection_kicker: "Editorial Category",
    title: "Women's Atelier",
    description:
      "A curated selection of architectural silhouettes and natural textiles, designed for the modern form.",
    primary_cta_label: "Open Women's Atelier",
    primary_cta_href: "/categories/Shop%20Women",
    secondary_cta_label: "View Archive",
    secondary_cta_href: "/products",
    background_image: womenImages.hero,
    quote_kicker: "Atelier Note",
    quote_body:
      "Quiet luxury, sculptural drape, and soft precision brought into a more spacious editorial layout.",
    accent: "#c19b92",
    arrivals_kicker: "Women's Edit",
    arrivals_title: "Quiet Luxury Pieces",
  },
  {
    segment_slug: "accessories",
    collection_kicker: "Editorial Category",
    title: "Accessories Atelier",
    description:
      "A curated collection of tactile essentials, defined by material integrity and architectural form. Crafted for the discerning individual.",
    primary_cta_label: "Open Accessories Atelier",
    primary_cta_href: "/categories/Accessories",
    secondary_cta_label: "View Archive",
    secondary_cta_href: "/products",
    background_image: accessoriesImages.hero,
    quote_kicker: "The Master Artisan",
    quote_body: "True luxury is found in the hidden details of the stitch.",
    accent: "#b18f75",
    arrivals_kicker: "Accessories Edit",
    arrivals_title: "Tactile Objects in Focus",
  },
];

export const categoryTiles = [
  {
    segment_slug: "all-archive",
    position: 1,
    eyebrow: "Editorial Category",
    title: "Men's Atelier",
    subtitle: "Architectural tailoring, knit structure, and grounded outerwear for the modern artisan.",
    image_url: homeImages.menTile,
    cta_label: "Open Men's Atelier",
    cta_href: "/categories/Shop%20Men",
  },
  {
    segment_slug: "all-archive",
    position: 2,
    eyebrow: "Editorial Category",
    title: "Women's Atelier",
    subtitle: "Curated silhouettes, tactile textiles, and a softer line for the modern form.",
    image_url: homeImages.womenTile,
    cta_label: "Open Women's Atelier",
    cta_href: "/categories/Shop%20Women",
  },
  {
    segment_slug: "all-archive",
    position: 3,
    eyebrow: "Editorial Category",
    title: "Footwear Atelier",
    subtitle: "Handcrafted performance and sculptural form for the modern explorer.",
    image_url: homeImages.footwearTile,
    cta_label: "Open Footwear Atelier",
    cta_href: "/categories/Footwear",
  },
  {
    segment_slug: "all-archive",
    position: 4,
    eyebrow: "Editorial Category",
    title: "Accessories Atelier",
    subtitle: "Objects, bags, and finishing pieces with architectural calm and material depth.",
    image_url: homeImages.accessoriesTile,
    cta_label: "Open Accessories Atelier",
    cta_href: "/categories/Accessories",
  },
  {
    segment_slug: "nam",
    position: 1,
    eyebrow: "New Arrival",
    title: "Sculpted Linen Shirt",
    subtitle: "Italian linen blend with a clean, editorial line.",
    image_url: menImages.one,
    cta_label: "View Piece",
    cta_href: "/categories/Shop%20Men",
  },
  {
    segment_slug: "nam",
    position: 2,
    eyebrow: "Limited Edition",
    title: "Structured Atelier Jacket",
    subtitle: "100% merino wool cut for a stronger shoulder and quiet authority.",
    image_url: menImages.two,
    cta_label: "View Jacket",
    cta_href: "/categories/Shop%20Men",
  },
  {
    segment_slug: "nam",
    position: 3,
    eyebrow: "Tailoring",
    title: "Modern Drape Trousers",
    subtitle: "Fine serge cotton with a looser break and softened waistline.",
    image_url: menImages.three,
    cta_label: "View Trousers",
    cta_href: "/categories/Shop%20Men",
  },
  {
    segment_slug: "nam",
    position: 4,
    eyebrow: "Knitwear",
    title: "Atelier Knit Polo",
    subtitle: "Sea Island cotton knit that keeps the palette calm and tactile.",
    image_url: menImages.four,
    cta_label: "View Knitwear",
    cta_href: "/categories/Shop%20Men",
  },
  {
    segment_slug: "nu",
    position: 1,
    eyebrow: "New Arrival",
    title: "Ethereal Silk Slip",
    subtitle: "A lightweight shape that holds the softer side of the women's edit.",
    image_url: womenImages.one,
    cta_label: "View Dress",
    cta_href: "/categories/Shop%20Women",
  },
  {
    segment_slug: "nu",
    position: 2,
    eyebrow: "Limited",
    title: "Architectural Overcoat",
    subtitle: "Outerwear with a sharper line and a sculpted stance.",
    image_url: womenImages.two,
    cta_label: "View Outerwear",
    cta_href: "/categories/Shop%20Women",
  },
  {
    segment_slug: "nu",
    position: 3,
    eyebrow: "Knitwear",
    title: "Cloud Cashmere Crew",
    subtitle: "A softer knit layer that keeps the edit warm without visual noise.",
    image_url: womenImages.three,
    cta_label: "View Knitwear",
    cta_href: "/categories/Shop%20Women",
  },
  {
    segment_slug: "nu",
    position: 4,
    eyebrow: "Bottoms",
    title: "Sculptural Pleated Skirt",
    subtitle: "A clean pleated profile that keeps the women's story precise and light.",
    image_url: womenImages.four,
    cta_label: "View Skirt",
    cta_href: "/categories/Shop%20Women",
  },
  {
    segment_slug: "accessories",
    position: 1,
    eyebrow: "Limited Edition",
    title: "Atelier Tote",
    subtitle: "Vegetable tanned leather with a strong silhouette and quiet finish.",
    image_url: accessoriesImages.one,
    cta_label: "View Tote",
    cta_href: "/categories/Accessories",
  },
  {
    segment_slug: "accessories",
    position: 2,
    eyebrow: "Essential",
    title: "Aurora Wrap",
    subtitle: "Organic raw silk staged as a tactile accent in the accessory story.",
    image_url: accessoriesImages.two,
    cta_label: "View Wrap",
    cta_href: "/categories/Accessories",
  },
  {
    segment_slug: "accessories",
    position: 3,
    eyebrow: "Leather Detail",
    title: "Cintura Belt",
    subtitle: "Full grain saddle leather shaped to feel precise and durable.",
    image_url: accessoriesImages.three,
    cta_label: "View Belt",
    cta_href: "/categories/Accessories",
  },
  {
    segment_slug: "accessories",
    position: 4,
    eyebrow: "Leather Detail",
    title: "Vault Clutch",
    subtitle: "Nappa leather in a more compact silhouette for evening structure.",
    image_url: accessoriesImages.four,
    cta_label: "View Clutch",
    cta_href: "/categories/Accessories",
  },
];

export const callout = [
  {
    segment_slug: "all-archive",
    eyebrow: "Editorial System",
    title: "Digital Precision, Analogue Soul.",
    body:
      "Beyond the silhouette lies a sophisticated technological core. Our microservice-driven inventory architecture ensures that every piece in our Digital Atelier is accounted for in real time.",
    image_url: homeImages.callout,
  },
  {
    segment_slug: "nam",
    eyebrow: "Men's Atelier",
    title: "Structure, material depth, and quieter authority.",
    body:
      "This tab reuses the home layout while pulling imagery and copy from the Men's Atelier direction in Stitch, so the UI stays fixed and the editorial content stays fluid.",
    image_url: menImages.five,
  },
  {
    segment_slug: "nu",
    eyebrow: "Women's Atelier",
    title: "Quiet luxury, defined by purpose.",
    body:
      "The women's story leans into sculptural softness and natural textiles, while the workbook keeps the copy and images easy to refresh without reworking the layout.",
    image_url: womenImages.five,
  },
  {
    segment_slug: "accessories",
    eyebrow: "Accessories Atelier",
    title: "Objects defined by hidden detail and material clarity.",
    body:
      "Every card and image on this tab can be swapped by editing the workbook, while the page keeps the same spacious editorial rhythm as the Stitch reference.",
    image_url: accessoriesImages.five,
  },
];

export const calloutMetrics = [
  {
    segment_slug: "all-archive",
    position: 1,
    value: "0.4s",
    label: "Inventory Latency",
  },
  {
    segment_slug: "all-archive",
    position: 2,
    value: "100%",
    label: "Atelier Sourcing",
  },
  {
    segment_slug: "nam",
    position: 1,
    value: "12",
    label: "Results Shown",
  },
  {
    segment_slug: "nam",
    position: 2,
    value: "04",
    label: "Core Categories",
  },
  {
    segment_slug: "nu",
    position: 1,
    value: "63",
    label: "Pieces Available",
  },
  {
    segment_slug: "nu",
    position: 2,
    value: "05",
    label: "Sizes Visible",
  },
  {
    segment_slug: "accessories",
    position: 1,
    value: "05",
    label: "Object Types",
  },
  {
    segment_slug: "accessories",
    position: 2,
    value: "04",
    label: "Core Materials",
  },
];

export const products = [
  {
    segment_slug: "all-archive",
    position: 1,
    product_id: "archive-001",
    eyebrow: "Outerwear",
    brand: "ND Shop",
    name: "Merino Hearth Coat",
    price: 890,
    size_tag: "Outerwear",
    fit_note: "Featured coat from the Stitch home screen's seasonal essentials rail.",
    image_url: homeImages.callout,
    href: "/products",
  },
  {
    segment_slug: "all-archive",
    position: 2,
    product_id: "archive-002",
    eyebrow: "Footwear",
    brand: "ND Shop",
    name: "The Alpine Chelsea",
    price: 450,
    size_tag: "Boots",
    fit_note: "A sharper boot profile to mirror the footwear edit from Stitch.",
    image_url: homeImages.footwearTile,
    href: "/products",
  },
  {
    segment_slug: "all-archive",
    position: 3,
    product_id: "archive-003",
    eyebrow: "Accessories",
    brand: "ND Shop",
    name: "Raw Cashmere Scarf",
    price: 225,
    size_tag: "Cashmere",
    fit_note: "Accessory pick aligned to the curated accessory block on the Stitch home page.",
    image_url: homeImages.accessoriesTile,
    href: "/products",
  },
  {
    segment_slug: "all-archive",
    position: 4,
    product_id: "archive-004",
    eyebrow: "Knitwear",
    brand: "ND Shop",
    name: "Hearthstone Knit",
    price: 340,
    size_tag: "Knitwear",
    fit_note: "A quieter knit used to round out the editorial arrivals rail.",
    image_url: homeImages.womenTile,
    href: "/products",
  },
  {
    segment_slug: "nam",
    position: 1,
    product_id: "men-001",
    eyebrow: "New Arrival",
    brand: "ND Atelier",
    name: "Sculpted Linen Shirt",
    price: 420,
    size_tag: "Italian Linen Blend",
    fit_note: "Lightweight structure and a cleaner vertical line.",
    image_url: menImages.one,
    href: "/categories/Shop%20Men",
  },
  {
    segment_slug: "nam",
    position: 2,
    product_id: "men-002",
    eyebrow: "Limited Edition",
    brand: "ND Atelier",
    name: "Structured Atelier Jacket",
    price: 1250,
    size_tag: "100% Merino Wool",
    fit_note: "The anchor outerwear piece for the Men's Atelier story.",
    image_url: menImages.two,
    href: "/categories/Shop%20Men",
  },
  {
    segment_slug: "nam",
    position: 3,
    product_id: "men-003",
    eyebrow: "Tailoring",
    brand: "ND Atelier",
    name: "Modern Drape Trousers",
    price: 380,
    size_tag: "Fine Serge Cotton",
    fit_note: "A softer trouser shape to balance the sharper outer layers.",
    image_url: menImages.three,
    href: "/categories/Shop%20Men",
  },
  {
    segment_slug: "nam",
    position: 4,
    product_id: "men-004",
    eyebrow: "Knitwear",
    brand: "ND Atelier",
    name: "Atelier Knit Polo",
    price: 290,
    size_tag: "Sea Island Cotton",
    fit_note: "A quiet knit that keeps the men's rail warm and understated.",
    image_url: menImages.four,
    href: "/categories/Shop%20Men",
  },
  {
    segment_slug: "nu",
    position: 1,
    product_id: "women-001",
    eyebrow: "New Arrival",
    brand: "ND Atelier",
    name: "Ethereal Silk Slip",
    price: 340,
    size_tag: "Dresses",
    fit_note: "A lightweight silhouette used as the lead piece in the Women's Atelier grid.",
    image_url: womenImages.one,
    href: "/categories/Shop%20Women",
  },
  {
    segment_slug: "nu",
    position: 2,
    product_id: "women-002",
    eyebrow: "Limited",
    brand: "ND Atelier",
    name: "Architectural Overcoat",
    price: 1250,
    size_tag: "Outerwear",
    fit_note: "Sharper outerwear line pulled directly from the Stitch screen reference.",
    image_url: womenImages.two,
    href: "/categories/Shop%20Women",
  },
  {
    segment_slug: "nu",
    position: 3,
    product_id: "women-003",
    eyebrow: "Knitwear",
    brand: "ND Atelier",
    name: "Cloud Cashmere Crew",
    price: 280,
    size_tag: "Knitwear",
    fit_note: "A softer knit layer that keeps the women's tab calm and tactile.",
    image_url: womenImages.three,
    href: "/categories/Shop%20Women",
  },
  {
    segment_slug: "nu",
    position: 4,
    product_id: "women-004",
    eyebrow: "Bottoms",
    brand: "ND Atelier",
    name: "Sculptural Pleated Skirt",
    price: 490,
    size_tag: "Bottoms",
    fit_note: "Pleated movement with a cleaner, more architectural waistline.",
    image_url: womenImages.four,
    href: "/categories/Shop%20Women",
  },
  {
    segment_slug: "accessories",
    position: 1,
    product_id: "acc-001",
    eyebrow: "Limited Edition",
    brand: "ND Atelier",
    name: "Atelier Tote",
    price: 840,
    size_tag: "Vegetable Tanned Leather",
    fit_note: "Large leather object positioned as the lead piece in Accessories Atelier.",
    image_url: accessoriesImages.one,
    href: "/categories/Accessories",
  },
  {
    segment_slug: "accessories",
    position: 2,
    product_id: "acc-002",
    eyebrow: "Essential",
    brand: "ND Atelier",
    name: "Aurora Wrap",
    price: 215,
    size_tag: "Organic Raw Silk",
    fit_note: "A lighter textile accent to soften the accessory rail.",
    image_url: accessoriesImages.two,
    href: "/categories/Accessories",
  },
  {
    segment_slug: "accessories",
    position: 3,
    product_id: "acc-003",
    eyebrow: "Leather Detail",
    brand: "ND Atelier",
    name: "Cintura Belt",
    price: 165,
    size_tag: "Full Grain Saddle Leather",
    fit_note: "Structured belt detail pulled from the Stitch accessory catalog.",
    image_url: accessoriesImages.three,
    href: "/categories/Accessories",
  },
  {
    segment_slug: "accessories",
    position: 4,
    product_id: "acc-004",
    eyebrow: "Leather Detail",
    brand: "ND Atelier",
    name: "Vault Clutch",
    price: 420,
    size_tag: "Nappa Leather",
    fit_note: "Compact Nappa leather shape used to finish the accessory story.",
    image_url: accessoriesImages.four,
    href: "/categories/Accessories",
  },
];

export const categoryPages = [
  {
    slug: "men-atelier",
    nav_label: "Men",
    route_aliases: "Shop Men|shop-men|Men|men",
    hero_eyebrow: "The Men's",
    hero_title: "Men's Atelier",
    hero_description:
      "An architectural study in silhouette and structure. Crafted for the modern artisan with a steadier, darker editorial tone.",
    hero_image_url: menImages.hero,
    hero_image_alt:
      "Close-up of dark wool fabric and tailored structure in the Men's Atelier",
    quote_body:
      "Structure, restraint, and material depth staged with a quieter editorial rhythm.",
    quote_author: "ND Atelier",
    story_eyebrow: "Material Study",
    story_title: "The Obsidian Overcoat",
    story_body:
      "Outerwear anchors the men's edit with denser texture, stronger shoulders, and a cleaner break through the full silhouette.",
    story_image_url: menImages.five,
    story_image_alt: "Black luxury overcoat silhouette on a dark moody background",
    story_cta_label: "View Outerwear",
    story_cta_href: "/categories/Shop%20Men",
    results_label: "Showing %count% results",
    sort_label: "Sort by: Relevance",
    footer_note:
      "Workbook-driven category page aligned to the Men's Atelier screen in Stitch.",
  },
  {
    slug: "women-atelier",
    nav_label: "Women",
    route_aliases: "Shop Women|shop-women|Women|women",
    hero_eyebrow: "The Women's",
    hero_title: "Women's Atelier",
    hero_description:
      "Quiet luxury, sculptural drape, and natural fibers arranged with more room to breathe and a calmer editorial pace.",
    hero_image_url: womenImages.hero,
    hero_image_alt:
      "Close-up of ethereal cream silk fabric draping in a softly lit atelier",
    quote_body: "Quiet luxury, defined by purpose.",
    quote_author: "ND Atelier",
    story_eyebrow: "The Craftsmanship",
    story_title: "Soft drape, clear line, grounded warmth.",
    story_body:
      "The women's story holds its softness without losing structure, balancing fluid dresses with sharper outerwear and richer texture.",
    story_image_url: womenImages.five,
    story_image_alt: "Wide atelier scene with natural light and tactile fabric study",
    story_cta_label: "Read the Story",
    story_cta_href: "/categories/Shop%20Women",
    results_label: "Showing %count% pieces",
    sort_label: "Sort By",
    footer_note:
      "Workbook-driven category page aligned to the Women's Atelier screen in Stitch.",
  },
  {
    slug: "footwear-atelier",
    nav_label: "Footwear",
    route_aliases: "Footwear|footwear",
    hero_eyebrow: "The Digital Atelier",
    hero_title: "Footwear Atelier",
    hero_description:
      "Handcrafted performance, sculptural form, and material precision for the modern explorer.",
    hero_image_url: footwearImages.hero,
    hero_image_alt:
      "Premium leather shoemaking tools and footwear materials in a bright artisan workshop",
    quote_body:
      "\"Luxury is not the absence of imperfection, but the presence of character.\"",
    quote_author: "Master Shoemaker, ND Atelier",
    story_eyebrow: "The Heritage Series",
    story_title: "Heritage craft, modern proportion.",
    story_body:
      "Leather, edge finishing, and hardware carry the footwear story with a more tactile, workshop-led tone throughout the page.",
    story_image_url: footwearImages.four,
    story_image_alt: "Abstract editorial shot of leather boots and workshop detail",
    story_cta_label: "Discover Craft",
    story_cta_href: "/categories/Footwear",
    results_label: "Showing %count% results",
    sort_label: "Sort by: Relevance",
    footer_note:
      "Workbook-driven category page aligned to the Footwear Atelier screen in Stitch.",
  },
  {
    slug: "accessories-atelier",
    nav_label: "Accessories",
    route_aliases: "Accessories|accessories",
    hero_eyebrow: "Accessories",
    hero_title: "Accessories Atelier",
    hero_description:
      "Objects, bags, and finishing pieces shaped by material integrity and quieter architectural form.",
    hero_image_url: accessoriesImages.hero,
    hero_image_alt:
      "Close-up of vegetable tanned leather and fine stitching tools in warm light",
    quote_body: "True luxury is found in the hidden details of the stitch.",
    quote_author: "The Master Artisan",
    story_eyebrow: "Material Focus",
    story_title: "Objects designed to finish the silhouette.",
    story_body:
      "From vegetable tanned leather to raw silk, the accessory page keeps the same airy composition while every object stays editable in the workbook.",
    story_image_url: accessoriesImages.five,
    story_image_alt: "Monochromatic scarf and accessory study in a cream-toned set",
    story_cta_label: "Discover Objects",
    story_cta_href: "/categories/Accessories",
    results_label: "Showing %count% results",
    sort_label: "Sort by: Relevance",
    footer_note:
      "Workbook-driven category page aligned to the Accessories Atelier screen in Stitch.",
  },
];

export const categoryFilters = [
  {
    page_slug: "men-atelier",
    position: 1,
    filter_key: "category",
    label: "Category",
    options: "Shirts|Outerwear|Trousers|Knitwear",
    default_value: "",
  },
  {
    page_slug: "men-atelier",
    position: 2,
    filter_key: "size",
    label: "Size",
    options: "S|M|L|XL",
    default_value: "",
  },
  {
    page_slug: "men-atelier",
    position: 3,
    filter_key: "price",
    label: "Price Range",
    options: "$150-$500|$500-$1000|$1000+",
    default_value: "",
  },
  {
    page_slug: "women-atelier",
    position: 1,
    filter_key: "category",
    label: "Categories",
    options: "Dresses|Tops|Bottoms|Outerwear",
    default_value: "",
  },
  {
    page_slug: "women-atelier",
    position: 2,
    filter_key: "size",
    label: "Size",
    options: "XS|S|M|L|XL",
    default_value: "",
  },
  {
    page_slug: "women-atelier",
    position: 3,
    filter_key: "palette",
    label: "Palette",
    options: "Cream|Forest|Stone|Charcoal",
    default_value: "",
  },
  {
    page_slug: "footwear-atelier",
    position: 1,
    filter_key: "type",
    label: "Type",
    options: "Boots|Sneakers|Loafers|Sandals",
    default_value: "",
  },
  {
    page_slug: "footwear-atelier",
    position: 2,
    filter_key: "size",
    label: "Size",
    options: "39|40|41|42|43",
    default_value: "",
  },
  {
    page_slug: "footwear-atelier",
    position: 3,
    filter_key: "material",
    label: "Material",
    options: "Calfskin|Suede|Grain Leather|Bridle Leather",
    default_value: "",
  },
  {
    page_slug: "accessories-atelier",
    position: 1,
    filter_key: "category",
    label: "Category",
    options: "All Objects|Bags|Belts|Jewelry|Scarves",
    default_value: "",
  },
  {
    page_slug: "accessories-atelier",
    position: 2,
    filter_key: "material",
    label: "Material",
    options: "Raw Silk|Vachetta|Sterling Silver|Cashmere|Nappa Leather",
    default_value: "",
  },
];

export const categoryPageProducts = [
  {
    page_slug: "men-atelier",
    position: 1,
    badge: "New Arrival",
    name: "Sculpted Linen Shirt",
    material: "Italian Linen Blend",
    price: 420,
    image_url: menImages.one,
    image_alt: "Cream tailored linen shirt in morning light",
    href: "/categories/Shop%20Men",
    filter_tags: "category:shirts|size:M|price:$150-$500",
  },
  {
    page_slug: "men-atelier",
    position: 2,
    badge: "Limited Edition",
    name: "Structured Atelier Jacket",
    material: "100% Merino Wool",
    price: 1250,
    image_url: menImages.two,
    image_alt: "Structured dark wool jacket with precise lapel detail",
    href: "/categories/Shop%20Men",
    filter_tags: "category:outerwear|size:L|price:$1000+",
  },
  {
    page_slug: "men-atelier",
    position: 3,
    badge: "Tailoring",
    name: "Modern Drape Trousers",
    material: "Fine Serge Cotton",
    price: 380,
    image_url: menImages.three,
    image_alt: "Folded olive trousers with sharp crease",
    href: "/categories/Shop%20Men",
    filter_tags: "category:trousers|size:M|price:$150-$500",
  },
  {
    page_slug: "men-atelier",
    position: 4,
    badge: "New Arrival",
    name: "Atelier Knit Polo",
    material: "Sea Island Cotton",
    price: 290,
    image_url: menImages.four,
    image_alt: "Dark green knit polo with horn buttons",
    href: "/categories/Shop%20Men",
    filter_tags: "category:knitwear|size:M|price:$150-$500",
  },
  {
    page_slug: "men-atelier",
    position: 5,
    badge: "Editorial Pick",
    name: "The Obsidian Overcoat",
    material: "Cashmere Blend",
    price: 1890,
    image_url: menImages.five,
    image_alt: "Black overcoat silhouette on a dark background",
    href: "/categories/Shop%20Men",
    filter_tags: "category:outerwear|size:L|price:$1000+",
  },
  {
    page_slug: "men-atelier",
    position: 6,
    badge: "Studio Essential",
    name: "Relaxed Cargo Trouser",
    material: "Brushed Twill",
    price: 340,
    image_url: homeImages.menTile,
    image_alt: "Khaki trouser texture and pocket detail",
    href: "/categories/Shop%20Men",
    filter_tags: "category:trousers|size:S|price:$150-$500",
  },
  {
    page_slug: "women-atelier",
    position: 1,
    badge: "New Arrival",
    name: "Ethereal Silk Slip",
    material: "Dresses",
    price: 340,
    image_url: womenImages.one,
    image_alt: "Model in a cream silk slip dress",
    href: "/categories/Shop%20Women",
    filter_tags: "category:dresses|size:S|palette:Cream",
  },
  {
    page_slug: "women-atelier",
    position: 2,
    badge: "Limited",
    name: "Architectural Overcoat",
    material: "Outerwear",
    price: 1250,
    image_url: womenImages.two,
    image_alt: "Deep forest tailored overcoat with sharp lines",
    href: "/categories/Shop%20Women",
    filter_tags: "category:outerwear|size:M|palette:Forest",
  },
  {
    page_slug: "women-atelier",
    position: 3,
    badge: "Knitwear",
    name: "Cloud Cashmere Crew",
    material: "Knitwear",
    price: 280,
    image_url: womenImages.three,
    image_alt: "Stone grey cashmere crew resting on a wooden chair",
    href: "/categories/Shop%20Women",
    filter_tags: "category:tops|size:M|palette:Stone",
  },
  {
    page_slug: "women-atelier",
    position: 4,
    badge: "Bottoms",
    name: "Sculptural Pleated Skirt",
    material: "Bottoms",
    price: 490,
    image_url: womenImages.four,
    image_alt: "Pleated charcoal skirt in motion through concrete architecture",
    href: "/categories/Shop%20Women",
    filter_tags: "category:bottoms|size:S|palette:Charcoal",
  },
  {
    page_slug: "women-atelier",
    position: 5,
    badge: "Bottoms",
    name: "Hearth Tapered Pant",
    material: "Bottoms",
    price: 320,
    image_url: homeImages.womenTile,
    image_alt: "High-end trouser detail in soft terracotta",
    href: "/categories/Shop%20Women",
    filter_tags: "category:bottoms|size:M|palette:Charcoal",
  },
  {
    page_slug: "women-atelier",
    position: 6,
    badge: "Outerwear",
    name: "Atelier Formal Blazer",
    material: "Outerwear",
    price: 850,
    image_url: womenImages.five,
    image_alt: "Structured blazer in forest green with atelier styling",
    href: "/categories/Shop%20Women",
    filter_tags: "category:outerwear|size:L|palette:Forest",
  },
  {
    page_slug: "footwear-atelier",
    position: 1,
    badge: "New Arrival",
    name: "Atelier Low Sneaker",
    material: "Smooth Italian Calfskin",
    price: 340,
    image_url: footwearImages.one,
    image_alt: "Minimalist white leather sneaker on an architectural background",
    href: "/categories/Footwear",
    filter_tags: "type:Sneakers|size:41|material:Calfskin",
  },
  {
    page_slug: "footwear-atelier",
    position: 2,
    badge: "Handcrafted",
    name: "Chelsea Field Boot",
    material: "Waxed Roughout Leather",
    price: 495,
    image_url: footwearImages.two,
    image_alt: "Dark brown leather chelsea boot with polished finish",
    href: "/categories/Footwear",
    filter_tags: "type:Boots|size:42|material:Suede",
  },
  {
    page_slug: "footwear-atelier",
    position: 3,
    badge: "Studio Classic",
    name: "Classic Penny Loafer",
    material: "Pebbled Grain Leather",
    price: 420,
    image_url: footwearImages.three,
    image_alt: "Classic black penny loafer with minimalist buckle detail",
    href: "/categories/Footwear",
    filter_tags: "type:Loafers|size:40|material:Grain Leather",
  },
  {
    page_slug: "footwear-atelier",
    position: 4,
    badge: "Workshop Build",
    name: "Moc Toe Service Boot",
    material: "English Bridle Leather",
    price: 560,
    image_url: footwearImages.four,
    image_alt: "High-top service boot in tobacco tan with premium hardware",
    href: "/categories/Footwear",
    filter_tags: "type:Boots|size:43|material:Bridle Leather",
  },
  {
    page_slug: "accessories-atelier",
    position: 1,
    badge: "Limited Edition",
    name: "Atelier Tote",
    material: "Vegetable Tanned Leather",
    price: 840,
    image_url: accessoriesImages.one,
    image_alt: "Minimalist leather tote in deep forest green",
    href: "/categories/Accessories",
    filter_tags: "category:Bags|material:Vachetta",
  },
  {
    page_slug: "accessories-atelier",
    position: 2,
    badge: "Essential",
    name: "Aurora Wrap",
    material: "Organic Raw Silk",
    price: 215,
    image_url: accessoriesImages.two,
    image_alt: "Artisanal silk scarf draped over a wooden chair",
    href: "/categories/Accessories",
    filter_tags: "category:Scarves|material:Raw Silk",
  },
  {
    page_slug: "accessories-atelier",
    position: 3,
    badge: "Leather Detail",
    name: "Cintura Belt",
    material: "Full Grain Saddle Leather",
    price: 165,
    image_url: accessoriesImages.three,
    image_alt: "Classic leather belt with brass buckle",
    href: "/categories/Accessories",
    filter_tags: "category:Belts|material:Vachetta",
  },
  {
    page_slug: "accessories-atelier",
    position: 4,
    badge: "Leather Detail",
    name: "Vault Clutch",
    material: "Nappa Leather",
    price: 420,
    image_url: accessoriesImages.four,
    image_alt: "Sculptural leather clutch in warm cognac tone",
    href: "/categories/Accessories",
    filter_tags: "category:Bags|material:Nappa Leather",
  },
  {
    page_slug: "accessories-atelier",
    position: 5,
    badge: "Limited Edition",
    name: "Obsidian Band",
    material: "925 Sterling Silver",
    price: 310,
    image_url: homeImages.callout,
    image_alt: "Hand-hammered sterling silver ring on dark stone",
    href: "/categories/Accessories",
    filter_tags: "category:Jewelry|material:Sterling Silver",
  },
  {
    page_slug: "accessories-atelier",
    position: 6,
    badge: "Soft Finish",
    name: "Mist Scarf",
    material: "Cashmere Blend",
    price: 190,
    image_url: accessoriesImages.five,
    image_alt: "Monochromatic scarf with delicate fringe detail",
    href: "/categories/Accessories",
    filter_tags: "category:Scarves|material:Cashmere",
  },
];

export const footerLinks = [
  {
    position: 1,
    label: "Sustainability",
    href: "/products",
  },
  {
    position: 2,
    label: "Atelier Services",
    href: "/products",
  },
  {
    position: 3,
    label: "Privacy",
    href: "/products",
  },
  {
    position: 4,
    label: "Terms",
    href: "/products",
  },
];
