server:
  port: "8084"
  host: "0.0.0.0"

database:
  host: "postgres"
  port: "5432"
  user: "admin"
  dbname: "ecommerce_order"
  sslmode: "disable"

redis:
  host: "redis"
  port: "6379"
  db: 0

rabbitmq:
  host: "rabbitmq"
  port: "5672"
  user: "admin"

tracing:
  enabled: true
  endpoint: "http://jaeger:4318"
  sample_ratio: 1.0

jwt:
  expiration: 24

services:
  product_service_grpc: "product-service:50052"
