server:
  port: "8085"
  host: "0.0.0.0"

database:
  host: "postgres"
  port: "5432"
  user: "admin"
  dbname: "ecommerce_payment"
  sslmode: "disable"

rabbitmq:
  host: "rabbitmq"
  port: "5672"
  user: "admin"

jwt:
  expiration: 24

payment_gateway:
  webhook_secret: "dev-momo-secret"
  momo_return_url: "http://localhost:4173/payments"
