server:
  port: "8081"
  host: "0.0.0.0"

database:
  host: "postgres"
  port: "5432"
  user: "admin"
  dbname: "ecommerce_user"
  sslmode: "disable"

redis:
  host: "redis"
  port: "6379"
  db: 0

tracing:
  enabled: true
  endpoint: "http://jaeger:4318"
  sample_ratio: 1.0

jwt:
  expiration: 24

grpc:
  port: "50051"

frontend:
  base_url: "http://localhost:4173"
