export { AddressesPageView } from "./addresses-page-view";
export { NotificationsPageView } from "./notifications-page-view";
export { OrderDetailPageView } from "./order-detail-page-view";
export { OrdersPageView } from "./orders-page-view";
export { PaymentsPageView } from "./payments-page-view";
export { ProfileDashboard } from "./profile-dashboard";
export { ReturnDetailPageView } from "./return-detail-page-view";
export { ReturnsPageView } from "./returns-page-view";
export { SecurityPageView } from "./security-page-view";
